function show_positionMask2d(yy)
% Usage ... show_positionMask2d(out_str)
%
% Without arguments, this function will looks for the saved position
% mat-file generated by positionMask2d_many (calls positionMask2d)

if (nargin==0),
  if exist('ZSer_summ_pos.mat','file'),
    yy='ZSer_summ_pos.mat';
    disp(sprintf('  loading %s',yy));
  else,
    [tmpname,tmppath]=uigetfile('*.*','Select PositionMask File to Open');
    yy=[tmppath,tmpname];
    disp(sprintf('  loading %s',yy));
  end
end;

if ischar(yy),
  load(yy),
  tmpvar=who; clear yy
  if exist('tmpname','var'),
    yy=ys; clear ys
  else,
    eval(sprintf('yy=%s;',tmpvar{1}));
  end;
end;

figure(1), clf,
for mm=1:length(yy.subIm),
    subplot(121), show(im_super(yy.mainIm,yy.mask{mm},0.5)), 
    subplot(122), show(yy.subIm{mm})
    maskEdge{mm}=edge(yy.mask{mm});
    pause,
end;

figure(1), clf,
im_overlay4(yy.mainIm,maskEdge),
