function [] = slider_plot()
% Plot different plots according to slider location.

S.fh = uifigure('units','pixels',...
              'position',[300 300 300 300],...
              'menubar','none',...
              'name','slider_plot',...
              'numbertitle','off',...
              'resize','off');    
S.x = 0:.01:1;  % For plotting.         
S.ax = axes('unit','pix',...
            'position',[20 80 260 210]);
S.LN = plot(S.x,S.x,'r');        
S.sl = uislider(S.fh,...
                 'position',[20 10 260 30],...
                 'limits',[1 10],'value',1,...
                 'valuechangingfcn',{@sl_call,S}); 

function [] = sl_call(varargin)
% Callback for the slider.
[h,S] = varargin{[1,3]};  % calling handle and data structure.
set(S.LN,'ydata',S.x.^get(h,'value'))